[package]
name = "trainphonet"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
tensorflow = "0.14.0"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"

[features]
tensorflow_gpu = ["tensorflow/tensorflow_gpu"]
