[package]
name = "prepare"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
audrey = "0.2.0"
rustfft = "3.0"
serde-big-array = "0.2.0"
